### ISSUE TITLE
Validation fails with petstore sample.

### ISSUE THREAD

**Issue by toshi38** [BigstickCarpet/swagger-express-middleware#91]
# Problem
I'm getting errors when I attempt to use "required" properties in the swagger documents.  I have tried from both postman/curl and with various forms of required:

```
required: [name, id, ...]
...
```

```
required:
  - name
  - id
```
```
properties:
  id:
    type: string
    required: true
```

With all of these different styles I run into the same issue, I get a ValidationError for "Missing required property: <prop name>".  Without the `required` it all works as expected and I can POST fine.

So I thought I'd try with the example that has some required properties.  I decided to try to POST a pet as shown below.

It's quite possible I'm doing something silly.  Let me know if that's the case.

# Reproduction steps
## Setup:
```
cd test-sem/
npm install express
npm install swagger-express-middleware
cd node_modules/swagger-express-middleware/samples/
node sample1.js
```

## Result:
Error for missing required property name: (from another terminal)
```
stephen@stephen-VirtualBox:~/code/test-sem/node_modules/swagger-express-middleware/samples$ curl -H "Content-Type: application/json" -X POST -d '{"pet": {"name": "testname", "type": "awesome"}}' http://localhost:8080/pets
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: The &quot;pet&quot; body parameter is invalid ({&quot;pet&quot;:{&quot;name&quot;:&quot;testname&quot;,&quot;type&quot;:&quot;awesome&quot;}}) <br>JSON Schema validation error. <br>Data path: &quot;&quot; <br>Schema path: &quot;/required/0&quot; <br>Missing required property: name<br> &nbsp; &nbsp;at ono (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/ono/lib/index.js:62:17)<br> &nbsp; &nbsp;at parseParameter (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:146:11)<br> &nbsp; &nbsp;at /home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:93:18<br> &nbsp; &nbsp;at Array.some (native)<br> &nbsp; &nbsp;at parseBodyParam (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:77:10)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/index.js:275:10) <br><br>Error: JSON Schema validation error. <br>Data path: &quot;&quot; <br>Schema path: &quot;/required/0&quot; <br>Missing required property: name<br> &nbsp; &nbsp;at ono (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/ono/lib/index.js:62:17)<br> &nbsp; &nbsp;at jsonValidate (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:207:11)<br> &nbsp; &nbsp;at parseObject (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:505:3)<br> &nbsp; &nbsp;at JsonSchema.parse (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:92:14)<br> &nbsp; &nbsp;at parseParameter (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:143:35)<br> &nbsp; &nbsp;at /home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:93:18<br> &nbsp; &nbsp;at Array.some (native)<br> &nbsp; &nbsp;at parseBodyParam (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:77:10)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/express/lib/router/index.js:317:13) <br><br>Error<br> &nbsp; &nbsp;at new ValidationError (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:1461:12)<br> &nbsp; &nbsp;at ValidatorContext.createError (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:359:14)<br> &nbsp; &nbsp;at ValidatorContext.validateObjectRequiredProperties (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:993:22)<br> &nbsp; &nbsp;at ValidatorContext.validateObject (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:960:11)<br> &nbsp; &nbsp;at ValidatorContext.validateAll (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:603:11)<br> &nbsp; &nbsp;at Object.validate (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/tv4/tv4.js:1573:24)<br> &nbsp; &nbsp;at jsonValidate (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:202:11)<br> &nbsp; &nbsp;at parseObject (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:505:3)<br> &nbsp; &nbsp;at JsonSchema.parse (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:92:14)<br> &nbsp; &nbsp;at parseParameter (/home/stephen/code/nodejs-express-courses/microservices-course/demos/05-swagger-express/node_modules/swagger-express-middleware/lib/param-parser.js:143:35)</pre>
</body>
</html>
```

**Comment by toshi38** [comment]
Fwiw I went and fixed this locally but it causes a lot of other errors in the tests.

So the question is if you have something like:

```
      post:
        description: Creates a new pet in the store.
        operationId: addPet
        security:
          - petStoreBasic: []
            petStoreApiKey: []
          - petStoreOAuth: [view, edit, create]
        produces:
          - application/json
        parameters:
          - name: PetData
            in: body
            description: Pet to add to the store
            required: true
            schema:
              $ref: "#/definitions/pet"
        responses:
          201:
            description: pet response
            headers:
              Location:
                type: string
                description: Swagger-Express-Middleware will automatically set this header appropriately
          409:
            description: new pet conflicts with an existing pet (i.e. they have the same name)
          default:
            description: unexpected error
            schema:
              $ref: "#/definitions/error"
```

when you pass in the body do you expect to have:

```
{
  pet: {
    name: "name"
  }
}
```

OR 

```
{
  name: "name"
}
```

I would expect the first since you could have multiple parameters in the body like so:

```
      post:
        description: Creates a new pet in the store.
        operationId: addPet
        security:
          - petStoreBasic: []
            petStoreApiKey: []
          - petStoreOAuth: [view, edit, create]
        produces:
          - application/json
        parameters:
          - name: sample
            in: body
            description: test stuff
            required: true
            type: string
          - name: PetData
            in: body
            description: Pet to add to the store
            required: true
            schema:
              $ref: "#/definitions/pet"
```

**Comment by toshi38** [comment]
From swagger spec... 

> There can be one "body" parameter at most.
